#!/usr/bin/env php
<?php
$argv = $_SERVER['argv'];
$command = $argv[1] ?? null;

if ($command !== 'run') {
    echo "Usage: php drift run [--host:port]\n";
    exit(1);
}


$host = '127.0.0.1';
$port = '8000';

if (isset($argv[2]) && str_starts_with($argv[2], '--')) {
    $arg = substr($argv[2], 2);
    if (str_contains($arg, ':')) {
        [$host, $port] = explode(':', $arg, 2);
    } else {
        $host = $arg;
    }
}

$publicDir = __DIR__ . '/public';

echo "Starting server at http://{$host}:{$port}\n";

$cmd = sprintf('php -S %s:%s -t "%s"', $host, $port, $publicDir);
passthru($cmd);
