#!/usr/bin/env php
<?php

define('DRIFT_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';
$app = require __DIR__ . '/bootstrap/app.php';

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use app\core\console\Kernel;

$kernel = new Kernel();

$status = $kernel->handle(new ArgvInput(), new ConsoleOutput());
$kernel->terminate(null, $status);

exit($status);
